language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt mock --use-mirrors"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run runtests.py"
after_success:
    - "coveralls"
notifications:
    email: false
